import Head from "next/head";
import styles from "../styles/Home.module.css";
import Home from "../components/Home";

export default function Main() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Varun_Patidar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
